task: unlearning                # 任务类型改为去学习
model: mlp                      
dataset: opendialkg             
mask_dir: save/partition/opendialkg-8 
save_dir: save/unlearning/opendialkg-mlp-8  
client_path: save/federated/opendialkg-mlp-8

epochs: 20
calibration_epochs: 5           # 校准训练轮次（推荐2-5）
learning_rate: 1e-2

# 联邦参数继承
n_client: 8                     # 保持客户端总数不变
split_item: False               # 保持相同数据分割设置
split_entity: False
split_word: False
split_dialog: True

# 验证参数
validate_after_unlearn: True    # 是否执行最终验证
test_on_retained: True          # 仅在保留客户端上测试
test_on_full: False             # 是否在全量数据上测试

# 日志配置（与原配置对称）
wandb_use: False
wandb_project: FedUnlCRS
wandb_name: unlearning-opendialkg-mlp-8