task: federated
model: mlp # mlp
dataset: opendialkg # hredial htgredial opendialkg durecdial
mask_dir: save/partition/opendialkg-8
save_dir: save/federated/opendialkg-mlp-8

epochs: 20
learning_rate: 1e-2

n_client: 8
split_item: False
split_entity: False
split_word: False
split_dialog: True

wandb_project: FedUnlCRS
wandb_name: federated-opendialkg-mlp-8