task: unlearning

model_name: hycorec # mlp hycorec
dataset_name: opendialkg # hredial htgredial opendialkg durecdial

partition_methon: random # random
partition_mode: conv # user conv item entity word

unlearning_layer:
  - [user, 8]
  - [conv, 8]
  - [item, 8]
  - [entity, 8]
  - [word, 8]
  - [item_hypergraph, 8]
  - [entity_hypergraph, 8]
  - [word_hypergraph, 8]
unlearning_sample_methon: random # random

n_client_per_proc: 1
n_proc: 8
n_client: 8

aggregate_methon: mean # mean
aggregate_rate: 0.0003

epochs: 8
batch_size: 32
learning_rate: 0.01

random_config:

model_config:
  mlp:
    hidden_dim: 256
  
  hycorec:
    num_bases: 8
    emb_dim: 256
    pooling_methon: Attn # Mean Attn
    mha_n_heads: 4